import type {
  StayCareAuditEvent,
  StayCareKpi,
  StayCarePartner,
  StayCareRole,
  StayCareSubscription,
  StayCareTask,
  StayCareTicket,
  StayCareWorker,
} from "@/lib/staycare/types"

export const roleLabels: Record<StayCareRole, string> = {
  sejoong_admin: "세중 서비스 관리자",
  sejoong_lawyer: "세중 담당 변호사",
  operator_manager: "운영 PM",
  operator_agent: "운영 코디네이터",
  employer_admin: "고용주 관리자",
  partner_specialist: "전문 파트너",
  worker: "근로자",
  auditor: "감사자",
}

export const demoWorkers: StayCareWorker[] = [
  {
    id: "SC-W-260701",
    name: "니말 페레라",
    nameEn: "Nimal Perera",
    nationality: "스리랑카",
    preferredLanguage: "සිංහල",
    visaType: "E-7",
    lifecycle: "onboarding",
    employer: "한빛조선 협력사",
    worksite: "거제 생산현장",
    role: "용접 기능인력",
    arrivalDate: "2026-07-27",
    visaExpiresAt: "2028-07-26",
    passportExpiresAt: "2031-02-18",
    foreignerRegistration: "scheduled",
    phoneStatus: "temporary",
    bankStatus: "prepared",
    insuranceStatus: "partial",
    accommodation: "거제 A기숙사 203호",
    riskScore: 38,
    riskLabel: "medium",
    checklistProgress: 68,
    subscriptionId: "SUB-260701",
    coordinator: "김서윤",
    nextAction: "외국인등록 방문 서류 최종확인",
    nextActionDue: "2026-07-30",
    tags: ["7/27 입국", "용접", "싱할라어"],
  },
  {
    id: "SC-W-260702",
    name: "카산 자야싱헤",
    nameEn: "Kasan Jayasinghe",
    nationality: "스리랑카",
    preferredLanguage: "English",
    visaType: "E-7",
    lifecycle: "onboarding",
    employer: "한빛조선 협력사",
    worksite: "거제 생산현장",
    role: "도장 기능인력",
    arrivalDate: "2026-07-27",
    visaExpiresAt: "2028-07-26",
    passportExpiresAt: "2030-09-03",
    foreignerRegistration: "scheduled",
    phoneStatus: "active",
    bankStatus: "prepared",
    insuranceStatus: "partial",
    accommodation: "거제 A기숙사 204호",
    riskScore: 24,
    riskLabel: "low",
    checklistProgress: 74,
    subscriptionId: "SUB-260702",
    coordinator: "김서윤",
    nextAction: "급여계좌 개설 동행 확인",
    nextActionDue: "2026-07-31",
    tags: ["7/27 입국", "도장", "영어"],
  },
  {
    id: "SC-W-260703",
    name: "딜란 페르난도",
    nameEn: "Dilan Fernando",
    nationality: "스리랑카",
    preferredLanguage: "සිංහල",
    visaType: "E-9",
    lifecycle: "active",
    employer: "대신테크",
    worksite: "울산 2공장",
    role: "제조 생산직",
    arrivalDate: "2026-04-11",
    visaExpiresAt: "2029-04-10",
    passportExpiresAt: "2030-11-20",
    foreignerRegistration: "issued",
    phoneStatus: "active",
    bankStatus: "active",
    insuranceStatus: "complete",
    accommodation: "울산 B기숙사 3동 108호",
    riskScore: 18,
    riskLabel: "low",
    checklistProgress: 100,
    subscriptionId: "SUB-260703",
    coordinator: "박정우",
    nextAction: "월간 생활 체크인",
    nextActionDue: "2026-07-24",
    tags: ["E-9", "제조", "안정"],
  },
  {
    id: "SC-W-260704",
    name: "라히루 쿠마라",
    nameEn: "Lahiru Kumara",
    nationality: "스리랑카",
    preferredLanguage: "සිංහල",
    visaType: "E-10",
    lifecycle: "active",
    employer: "청해수산",
    worksite: "통영 선원숙소",
    role: "어선원",
    arrivalDate: "2025-12-02",
    visaExpiresAt: "2027-12-01",
    passportExpiresAt: "2028-03-14",
    foreignerRegistration: "issued",
    phoneStatus: "active",
    bankStatus: "active",
    insuranceStatus: "complete",
    accommodation: "통영 선원숙소 1층 6호",
    riskScore: 72,
    riskLabel: "high",
    checklistProgress: 100,
    subscriptionId: "SUB-260704",
    coordinator: "이민호",
    nextAction: "임금명세·근로시간 긴급 점검",
    nextActionDue: "2026-07-19",
    tags: ["E-10", "임금문의", "P1"],
  },
  {
    id: "SC-W-260705",
    name: "사친 라나싱헤",
    nameEn: "Sachin Ranasinghe",
    nationality: "스리랑카",
    preferredLanguage: "English",
    visaType: "E-9",
    lifecycle: "active",
    employer: "대신테크",
    worksite: "울산 2공장",
    role: "제조 생산직",
    arrivalDate: "2026-04-11",
    visaExpiresAt: "2029-04-10",
    passportExpiresAt: "2029-07-07",
    foreignerRegistration: "issued",
    phoneStatus: "active",
    bankStatus: "active",
    insuranceStatus: "complete",
    accommodation: "울산 B기숙사 3동 109호",
    riskScore: 41,
    riskLabel: "medium",
    checklistProgress: 100,
    subscriptionId: "SUB-260705",
    coordinator: "박정우",
    nextAction: "기숙사 냉방 민원 처리확인",
    nextActionDue: "2026-07-20",
    tags: ["E-9", "숙소민원"],
  },
  {
    id: "SC-W-260706",
    name: "이샨 위제싱헤",
    nameEn: "Ishan Wijesinghe",
    nationality: "스리랑카",
    preferredLanguage: "සිංහල",
    visaType: "E-7-4",
    lifecycle: "active",
    employer: "세광정밀",
    worksite: "창원 본공장",
    role: "CNC 숙련기능인력",
    arrivalDate: "2021-09-15",
    visaExpiresAt: "2027-09-14",
    passportExpiresAt: "2029-01-29",
    foreignerRegistration: "issued",
    phoneStatus: "active",
    bankStatus: "active",
    insuranceStatus: "complete",
    accommodation: "창원 사택 502호",
    riskScore: 12,
    riskLabel: "low",
    checklistProgress: 100,
    subscriptionId: "SUB-260706",
    coordinator: "정하늘",
    nextAction: "장기체류 경로 정기검토",
    nextActionDue: "2026-08-01",
    tags: ["E-7-4", "숙련", "장기체류"],
  },
]

export const demoTasks: StayCareTask[] = [
  {
    id: "TASK-260901",
    workerId: "SC-W-260701",
    title: "외국인등록 방문서류 최종 점검",
    category: "immigration",
    status: "review_required",
    dueAt: "2026-07-30T10:00:00+09:00",
    assignee: "김서윤",
    organization: "StayCare 운영팀",
    evidenceRequired: true,
    slaHours: 24,
  },
  {
    id: "TASK-260902",
    workerId: "SC-W-260702",
    title: "급여계좌 개설 준비 및 동행 배정",
    category: "banking",
    status: "assigned",
    dueAt: "2026-07-31T09:00:00+09:00",
    assignee: "김서윤",
    organization: "StayCare 운영팀",
    evidenceRequired: true,
    slaHours: 48,
  },
  {
    id: "TASK-260903",
    workerId: "SC-W-260701",
    title: "EPS·사회보험 가입상태 확인",
    category: "insurance",
    status: "waiting_partner",
    dueAt: "2026-08-03T18:00:00+09:00",
    assignee: "오세진",
    organization: "노무 파트너",
    evidenceRequired: true,
    slaHours: 72,
  },
  {
    id: "TASK-260904",
    workerId: "SC-W-260704",
    title: "임금명세와 근로시간 자료 확보",
    category: "employment",
    status: "in_progress",
    dueAt: "2026-07-19T20:00:00+09:00",
    assignee: "이민호",
    organization: "StayCare 운영팀",
    evidenceRequired: true,
    slaHours: 4,
  },
  {
    id: "TASK-260905",
    workerId: "SC-W-260705",
    title: "기숙사 냉방설비 조치 결과 확인",
    category: "accommodation",
    status: "waiting_partner",
    dueAt: "2026-07-20T15:00:00+09:00",
    assignee: "박정우",
    organization: "숙소 운영사",
    evidenceRequired: true,
    slaHours: 24,
  },
  {
    id: "TASK-260906",
    workerId: "SC-W-260703",
    title: "7월 월간 생활 체크인",
    category: "employment",
    status: "assigned",
    dueAt: "2026-07-24T17:00:00+09:00",
    assignee: "박정우",
    organization: "StayCare 운영팀",
    evidenceRequired: false,
    slaHours: 72,
  },
]

export const demoTickets: StayCareTicket[] = [
  {
    id: "TKT-260118",
    workerId: "SC-W-260704",
    title: "최근 2개월 연장근로수당 확인 요청",
    category: "labor",
    priority: "P1",
    status: "in_progress",
    openedAt: "2026-07-19T08:12:00+09:00",
    firstResponseAt: "2026-07-19T08:24:00+09:00",
    owner: "이민호",
    escalationTarget: "세중 외국인·노동 담당",
    summary: "급여명세서와 실제 승선·근로시간 차이를 주장해 자료 확보 중입니다.",
  },
  {
    id: "TKT-260119",
    workerId: "SC-W-260705",
    title: "기숙사 냉방 작동 불량",
    category: "accommodation",
    priority: "P2",
    status: "waiting",
    openedAt: "2026-07-18T21:20:00+09:00",
    firstResponseAt: "2026-07-18T21:46:00+09:00",
    owner: "박정우",
    summary: "숙소 운영사에 긴급 점검을 요청했고 부품 교체 결과를 기다리고 있습니다.",
  },
  {
    id: "TKT-260120",
    workerId: "SC-W-260701",
    title: "공항 도착 후 유심 명의확인 문의",
    category: "communication",
    priority: "P3",
    status: "triaged",
    openedAt: "2026-07-19T11:05:00+09:00",
    firstResponseAt: "2026-07-19T11:42:00+09:00",
    owner: "김서윤",
    summary: "입국 직후 임시 유심과 외국인등록증 발급 후 정식 요금제 전환 절차를 안내할 예정입니다.",
  },
]

export const demoSubscriptions: StayCareSubscription[] = [
  {
    id: "SUB-260701",
    workerId: "SC-W-260701",
    plan: "Care Plus",
    billingCycle: "annual",
    payer: "sponsor",
    amount: 990000,
    status: "active",
    startedAt: "2026-07-20",
    renewsAt: "2027-07-20",
    includedSupportMinutes: 180,
    usedSupportMinutes: 25,
  },
  {
    id: "SUB-260702",
    workerId: "SC-W-260702",
    plan: "Care Plus",
    billingCycle: "annual",
    payer: "sponsor",
    amount: 990000,
    status: "active",
    startedAt: "2026-07-20",
    renewsAt: "2027-07-20",
    includedSupportMinutes: 180,
    usedSupportMinutes: 18,
  },
  {
    id: "SUB-260703",
    workerId: "SC-W-260703",
    plan: "Employer Managed",
    billingCycle: "monthly",
    payer: "employer",
    amount: 69000,
    status: "active",
    startedAt: "2026-04-01",
    renewsAt: "2026-08-01",
    includedSupportMinutes: 60,
    usedSupportMinutes: 42,
  },
  {
    id: "SUB-260704",
    workerId: "SC-W-260704",
    plan: "Care",
    billingCycle: "monthly",
    payer: "worker",
    amount: 79000,
    status: "grace_period",
    startedAt: "2026-01-02",
    renewsAt: "2026-07-22",
    includedSupportMinutes: 90,
    usedSupportMinutes: 96,
  },
  {
    id: "SUB-260705",
    workerId: "SC-W-260705",
    plan: "Employer Managed",
    billingCycle: "monthly",
    payer: "employer",
    amount: 69000,
    status: "active",
    startedAt: "2026-04-01",
    renewsAt: "2026-08-01",
    includedSupportMinutes: 60,
    usedSupportMinutes: 51,
  },
  {
    id: "SUB-260706",
    workerId: "SC-W-260706",
    plan: "Care Plus",
    billingCycle: "annual",
    payer: "worker",
    amount: 990000,
    status: "active",
    startedAt: "2026-02-01",
    renewsAt: "2027-02-01",
    includedSupportMinutes: 180,
    usedSupportMinutes: 65,
  },
]

export const demoPartners: StayCarePartner[] = [
  {
    id: "PARTNER-01",
    name: "법무법인 세중 외국인센터",
    type: "legal",
    region: "전국",
    status: "active",
    slaHours: 4,
    openTasks: 2,
    rating: 4.9,
    contact: "담당 변호사 배정형",
  },
  {
    id: "PARTNER-02",
    name: "남부 출입국행정 파트너",
    type: "immigration",
    region: "부산·울산·경남",
    status: "onboarding",
    slaHours: 24,
    openTasks: 3,
    rating: 4.7,
    contact: "등록 행정사 확인 필요",
  },
  {
    id: "PARTNER-03",
    name: "다온 공인노무사사무소",
    type: "labor",
    region: "전국 비대면",
    status: "active",
    slaHours: 8,
    openTasks: 1,
    rating: 4.8,
    contact: "노동·산재 티켓 전담",
  },
  {
    id: "PARTNER-04",
    name: "Sinhala Bridge",
    type: "translation",
    region: "전국",
    status: "active",
    slaHours: 2,
    openTasks: 4,
    rating: 4.9,
    contact: "싱할라어·영어 통역",
  },
  {
    id: "PARTNER-05",
    name: "Global SIM 공식판매점",
    type: "telecom",
    region: "인천·부산·김해공항",
    status: "active",
    slaHours: 12,
    openTasks: 2,
    rating: 4.6,
    contact: "공항 및 현장 개통",
  },
]

export const demoAuditEvents: StayCareAuditEvent[] = [
  {
    id: "AUD-001",
    occurredAt: "2026-07-19T14:32:00+09:00",
    actor: "김서윤",
    actorRole: "operator_agent",
    action: "여권 원문 미리보기",
    entity: "worker_document",
    entityId: "SC-W-260701/passport",
    reason: "외국인등록 방문서류 최종확인",
    severity: "warning",
  },
  {
    id: "AUD-002",
    occurredAt: "2026-07-19T13:10:00+09:00",
    actor: "이민호",
    actorRole: "operator_manager",
    action: "티켓 긴급도 P2 → P1 변경",
    entity: "ticket",
    entityId: "TKT-260118",
    reason: "반복 임금누락 주장과 출항 일정 임박",
    severity: "critical",
  },
  {
    id: "AUD-003",
    occurredAt: "2026-07-19T11:42:00+09:00",
    actor: "김서윤",
    actorRole: "operator_agent",
    action: "최초응답 기록",
    entity: "ticket",
    entityId: "TKT-260120",
    reason: "일반 통신문의 응답",
    severity: "info",
  },
  {
    id: "AUD-004",
    occurredAt: "2026-07-19T09:05:00+09:00",
    actor: "세중 관리자",
    actorRole: "sejoong_admin",
    action: "구독 유예기간 승인",
    entity: "subscription",
    entityId: "SUB-260704",
    reason: "고위험 근로자 보호를 위한 서비스 연속성 유지",
    severity: "warning",
  },
]

export const overviewKpis: StayCareKpi[] = [
  { label: "활성 회원", value: "126", delta: "+18 이번 달", tone: "positive" },
  { label: "7일 내 마감", value: "14", delta: "P1 1건 포함", tone: "warning" },
  { label: "진행중 티켓", value: "23", delta: "SLA 준수 96%", tone: "neutral" },
  { label: "월 반복매출", value: "₩10.8M", delta: "+12.4%", tone: "positive" },
]

export const statusLabel = {
  invited: "초대",
  onboarding: "온보딩",
  active: "이용중",
  paused: "일시중지",
  offboarding: "종료준비",
  closed: "종료",
  queued: "대기",
  assigned: "배정",
  in_progress: "처리중",
  waiting_member: "회원대기",
  waiting_partner: "파트너대기",
  review_required: "검토필요",
  completed: "완료",
  cancelled: "취소",
  trial: "체험",
  past_due: "미납",
  grace_period: "유예",
  suspended: "중지",
} as const

export function getWorker(workerId: string) {
  return demoWorkers.find((worker) => worker.id === workerId)
}

export function formatWon(value: number) {
  return new Intl.NumberFormat("ko-KR", {
    style: "currency",
    currency: "KRW",
    maximumFractionDigits: 0,
  }).format(value)
}
